# Inserts a blank line between shell prompts
add_newline = false

[git_branch]
symbol = " "

[hg_branch]
disabled = false
symbol = " "

[package]
symbol = " "

[c]
symbol = " "

[rust]
symbol = " "

[hostname]
ssh_symbol = '󰱠 '
trim_at = ''
